# The version of docker-compose being used.
version: '3'
services:
  backend:
    # Name the container
    container_name: bankme_backend
    # Build the Dockerfile image
    build: ./backend-app/
    # Expose the port 3001 to the host machine
    ports:
      - 3001:3001
    # Sets the working directory
    working_dir: /app/backend
    # Checks if the container is up and healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
    # Restarts the container if it crashes
    restart: always
    # Mount the backend directory in the machine and in the container
    volumes:
      - ./backend-app/src:/app/backend/src
    environment:
      - JWT_SECRET="banckmesecretkey"
  frontend:
    # Name the container
    container_name: bankme_frontend
    # Build the Dockerfile image
    build: ./frontend-app/
    # Expose the port 3000 to the host machine
    ports:
      - 3000:3000
    working_dir: /app/frontend
    # Checks if the container is up and healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
    # Restarts the container if it crashes
    restart: always
    # Mount the backend directory in the machine and in the container.
    volumes:
      - ./frontend-app/src:/app/frontend/src
    # Depends on the backend container to run.
    depends_on:
      - backend